name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
        with:
          node-version: '16.x'
      - run: npm install -g @angular/cli > /dev/null
      - run: npm install
      - run: ng build

  build_succeeded_notify:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - name: build has succceeded
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dev-builds
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#32BD77'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_MESSAGE: Build succeeded on this repository
          SLACK_TITLE: ${{ github.event.repository.name }}

  build_failed_notify:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}
    steps:
      - name: build has failed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dev-builds
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_MESSAGE: Build failed on this repository
          SLACK_TITLE: ${{ github.event.repository.name }}
